<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-05 05:52
=======
# Generated by Django 5.0.4 on 2024-05-06 14:27
>>>>>>> ae0b8d3a0db8bf0bfdf5a3847d438cf155e0ffe6

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number_of_pages', models.IntegerField()),
                ('publish_date', models.DateField()),
<<<<<<< HEAD
=======
                ('quantity', models.IntegerField()),
>>>>>>> ae0b8d3a0db8bf0bfdf5a3847d438cf155e0ffe6
            ],
        ),
    ]
