# Generated by Django 5.0.4 on 2024-05-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='judul',
            field=models.CharField(default='Judul Default', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='penulis',
            field=models.CharField(default='Penulis Default', max_length=100),
        ),
    ]
