# Generated by Django 5.0.4 on 2024-05-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0003_pembeli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal_beli', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_api.book')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_api.pembeli')),
            ],
        ),
    ]
